### ISSUE TITLE
Passing document.onkeydown to the game

### ISSUE THREAD

**Issue by kirillbunin** [gameeapp/gamee-emulator#3]
I'm using fullscreen controls and I'm trying to bind events to `document.onkeydown` for web version of the game, but the game does not react even to
```javascript
document.onkeydown = checkKey;

function checkKey(e) {
    console.log(e);
}
```
Do I have to listen to these events from gamee lib?

**Comment by EntityB** [comment]
Hey kirillbunin, 

I think there could be a problem if you start a game in the emulator the `focus` is on the top window and not on the iframe where the game is running. And iframe can't listen to the events happening on the parent window (going to fix this in the next release). 

Try to start the game and use the mouse to focus an iframe first. Then try to use the keyboard. Let me know if it works. If not, I will do the future investigation.

**Comment by EntityB** [comment]
https://github.com/gameeapp/gamee-emulator/issues/4

**Comment by kirillbunin** [comment]
I tried clicking on the game, then pressing keys, with no results. I eventually managed to [Tab] myself into the iframe, but it's pretty unpractical otherwise.

**Comment by EntityB** [comment]
@kirillbunin 
I just tested it on one of our samples with code:
```javascript
document.onkeydown = function () {
    console.log(arguments);
};
```

After I click big green play button, then I have to click one more time to have the focus. Then I capture key events without any problem. I can't help you more since I didn't manage to replicate your issue. Share the packed source code with me or provide more specific details if you need more help with this ;) michal.vodicka@gameeapp.com

_Win 10, Google Chrome 60.0.3112.113 64bit_

**Comment by kirillbunin** [comment]
Weird, works for me as well on Firefox, but the same version of Chrome does not. It still would be great if there was auto-focus so even on Firefox I wouldn't need to doubleclick. As the #4 states. So I'm closing this.
